typography_spectrum: 0.1892881609965116
color:
  saturation: 0.38744225515984
  brandStrength: 0.9361956370994449
  rhythmicContrast: 0.6117809312418103
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  lightness: 0.5170924412086606
layout_spectrum: 0
author:
  name: Alex Melnychuck
  email: amelnychuck@me.com
  url: alexmelnychuck.com
logo: null
name: The Radikal Group
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Radikal Group
description: ''
